//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwitterService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFollow
    {
        public int Id { get; set; }
        public Nullable<int> FollowerId { get; set; }
        public Nullable<int> FollowedId { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
