language: csharp
solution: TwitterService.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore TwitterService.sln
after_script:
  - nunit-console Tests/bin/Release/Tests.dll
